import { describe, expect, it } from "vitest";

import * as entry from "../src/index.js";

describe("@concordance-wiki/core", () => {
  it("exposes exactly its public API", () => {
    expect(Object.keys(entry).sort()).toEqual([
      "CONTRACT_METHOD",
      "CONTRACT_RELATION",
      "CONTRACT_UNREACHABLE",
      "DEFAULT_CONTRACT_CONFIDENCE",
      "PLUGIN_API_VERSION",
      "PluginDefinitionError",
      "PluginLoadError",
      "cachedContractPath",
      "commandExists",
      "compareContracts",
      "compareEntities",
      "compareFindings",
      "compareLinks",
      "compareProvenances",
      "compileGlobs",
      "createSpeakerNumbering",
      "declaredContracts",
      "definePlugin",
      "describeSchemaError",
      "detectPersonalMentions",
      "epochClock",
      "fingerprintOf",
      "fixedClock",
      "formatIssue",
      "formatValidation",
      "identifierFor",
      "importPlugin",
      "isWellFormedGlob",
      "loadContracts",
      "loadPlugins",
      "loadPseudonymDictionary",
      "memoryFileSystem",
      "nodeFileSystem",
      "nodeGit",
      "pagePath",
      "pageUrl",
      "parseConfig",
      "pseudonymizeSpeaker",
      "pseudonymizeText",
      "pseudonymizeTranscript",
      "readCachedContract",
      "readSchema",
      "resolveDuplicates",
      "serializeBuildLog",
      "shouldFail",
      "slugify",
      "sortCanonically",
      "summarize",
      "systemClock",
      "transcriptsPublished",
      "validateConfig",
      "writeCachedContract",
      "xmlRootOf",
    ]);
  });
});
