import { describe, expect, it } from "vitest";

import * as entry from "../src/index.js";

describe("@concordance-wiki/nlp", () => {
  it("exposes the language pack registry, the stopword and suffix file readers, text normalisation, the search tokens, the dictionary, the occurrence scan, the keyword discovery and its publication", () => {
    expect(Object.keys(entry).sort()).toEqual([
      "BURST_MIN_FILES",
      "BURST_PER_FILE",
      "CONTEXT_WIDTH",
      "HOMONYM_CHECK",
      "KEYWORD_TYPE",
      "LanguagePackError",
      "MORPHOLOGY_PENALTY",
      "NEIGHBOURHOOD_BASE",
      "POSITION_BASE",
      "SIMILAR_EXPRESSIONS_LIMIT",
      "SPREAD_MIN_FILES",
      "UNDEFINED_TERM_CHECK",
      "availableLocales",
      "buildAutomaton",
      "buildDictionary",
      "canonicalLocale",
      "compareMentions",
      "compareOccurrences",
      "comparisonForm",
      "comparisonWords",
      "confidenceDefaults",
      "confidenceFactors",
      "confidenceOf",
      "confidencePenalties",
      "definedExpressions",
      "dictionaryStopwords",
      "extractNgrams",
      "glossarySources",
      "isOnWordBoundaries",
      "keywordDefaults",
      "keywordEntities",
      "keywordForm",
      "keywordForms",
      "keywordOptions",
      "keywordPublicationDefaults",
      "keywordPublicationOptions",
      "languagePack",
      "loadLanguagePack",
      "loadStopwords",
      "loadSuffixes",
      "longestMatches",
      "occurrenceConfidence",
      "occurrenceContext",
      "publishKeywords",
      "registerLanguagePack",
      "resolveLocale",
      "scan",
      "scanDocument",
      "scoreCandidates",
      "searchTokens",
      "similarExpressions",
      "similarForm",
      "singularize",
      "tokenize",
      "undefinedTermFindings",
      "wordBoundaries",
    ]);
  });
});
