import { describe, expect, it } from "vitest";

import * as entry from "../src/index.js";

describe("@concordance-wiki/site", () => {
  it("exposes the slots, the default theme, the islands, the renderer, the stylesheet, the theme loader, the budget, the gallery, the accessibility checker and the contrast check", () => {
    expect(Object.keys(entry).sort()).toEqual([
      "A11Y_RULES",
      "CONTRAST_MINIMUMS",
      "CSS_LAYERS",
      "GALLERY_PAGE_BUDGET",
      "ISLAND_ELEMENT",
      "MODES",
      "MODE_SCRIPT",
      "MODE_STORAGE_KEY",
      "MODE_SWITCH_ISLAND",
      "ModeSwitch",
      "PROJECT_STYLESHEET",
      "REPOSITORY_URL",
      "SITE_STYLESHEET",
      "SLOT_NAMES",
      "ThemeContext",
      "ThemeResolutionError",
      "applyChoice",
      "baseStylesheet",
      "buildGallery",
      "bundleIslands",
      "checkAccessibility",
      "checkContrast",
      "chromeOf",
      "componentsStylesheet",
      "contrastPairs",
      "contrastRatio",
      "defaultComponents",
      "defaultIslands",
      "defaultTheme",
      "directionOf",
      "formatKilobytes",
      "galleryDocuments",
      "galleryFixtures",
      "galleryPages",
      "importThemeModule",
      "isSlotName",
      "island",
      "islandsUsed",
      "loadTheme",
      "measureBudget",
      "mountIslands",
      "nextChoice",
      "packageDirectoryOf",
      "packageRootOf",
      "projectStylesheet",
      "readChoice",
      "relativeLuminance",
      "renderDocument",
      "renderPage",
      "renderSlot",
      "resolveTheme",
      "siteStylesheet",
      "tokensStylesheet",
      "useSlot",
      "wireModeSwitch",
      "writeThemeAssets",
    ]);
  });
});
