/** Every visible string of the default theme, gathered so that a locale catalogue can replace them. */
export const labels = {
  skipToContent: "Skip to content",
  siteNavigation: "Site",
  siteSearch: "Site search",
  search: "Search",
  searchSubmit: "Search",
  version: "version",
  builtOn: "built on",
  credit: "Built with Concordance",
  colourScheme: "Colour scheme",
  modeSystem: "automatic",
  modeLight: "light",
  modeDark: "dark",
  entryPoints: "Entry points",
  sources: "sources",
  files: "files",
  dormant: "dormant",
  properties: "Properties",
  legendWritten: "link written in the note",
  legendRecognised: "word recognised at indexing",
  editInForge: "Edit in the forge",
  keyword: "keyword",
  noNote: "No note defines this word yet",
  passagesRecorded: "passages recorded",
  occurrences: "Occurrences",
  filesCount: "Files",
  sourcesCount: "Sources",
  passages: "Passages",
  line: "line",
  companions: "Accompanying words",
  similar: "Expressions with a similar form",
  similarLead: "Offered as a lead: nothing here asserts a relation.",
  mentions: "Mentions",
  writtenInNotes: "Written in notes",
  recognisedInFiles: "Recognised in files",
  noWrittenMention: "No note links here.",
  noRecognisedMention: "No file cites this entity.",
  showRemaining: "Show the remaining mentions",
  hideRemaining: "Hide the remaining mentions",
  neighbourhood: "Neighbourhood",
  neighbourhoodMap: "Map of the neighbourhood",
  neighbourhoodMapCaption: "The list below carries the same information as the map.",
  noNeighbour: "No neighbour recorded.",
  resultsFor: "results for",
  facets: "Facets",
  index: "Index",
  letters: "Letters",
  noteless: "no note",
  todo: "To do",
  documentsWithoutMarkdown: "Documents without a markdown representation",
  termsWithoutNote: "Words without a note",
  nothingToDo: "Nothing to do.",
} as const;
