/** Every visible string of the default theme, gathered so that a locale catalogue can replace them. */
export const labels = {
  skipToContent: "Skip to content",
  siteNavigation: "Site",
  siteSearch: "Site search",
  search: "Search",
  searchSubmit: "Search",
  version: "version",
  builtOn: "built on",
  credit: "Built with Concordance",
  colourScheme: "Colour scheme",
  modeSystem: "automatic",
  modeLight: "light",
  modeDark: "dark",
  entryPoints: "Entry points",
  sources: "sources",
  files: "files",
  dormant: "dormant",
  shortcuts: "Most cited words",
  sourceFreshness: "Freshness of the sources",
  properties: "Properties",
  legendWritten: "link written in the note",
  legendRecognised: "word recognised at indexing",
  source: "source:",
  editInForge: "Edit in the forge",
  occurrences: "Occurrences",
  filesCount: "Files",
  sourcesCount: "Sources",
  passages: "Passages",
  line: "line",
  companions: "Accompanying words",
  noCompanion: "No accompanying word recorded.",
  similar: "Expressions with a similar form",
  mentions: "Mentions",
  writtenInNotes: "Written in notes",
  recognisedInFiles: "Recognised in files",
  noWrittenMention: "No note links here.",
  noRecognisedMention: "No file cites this entity.",
  noMatchingMention: "No mention matches the filter.",
  mentionsControls: "Mentions controls",
  sortBy: "Sort",
  sortByFile: "by file",
  sortByCount: "by count",
  sortByLine: "by line",
  filter: "Filter",
  collapseAll: "Collapse all",
  expandAll: "Expand all",
  mentionsShown: "mentions shown",
  of: "of",
  showRemaining: "Show the remaining mentions",
  loadingRemaining: "Loading the remaining mentions",
  remainingUnavailable: "The remaining mentions could not be loaded",
  fullList: "Open the full list (JSON)",
  neighbourhood: "Neighbourhood",
  neighbourhoodMap: "Map of the neighbourhood",
  neighbourhoodMapCaption: "The list below carries the same information as the map.",
  noNeighbour: "No neighbour recorded.",
  neighboursInTotal: "neighbours in total, more than the map shows",
  seeMentions: "see the mentions panel",
  resultsFor: "results for",
  facets: "Facets",
  index: "Index",
  letters: "Letters",
  noteless: "no note",
  todo: "To do",
  documentsWithoutMarkdown: "Documents without a markdown representation",
  termsWithoutNote: "Words without a note",
  nothingToDo: "Nothing to do.",
  filesWithoutMarkdown: "Counted in files without a note.",
  occurrencesUnit: "Counted in occurrences, then in files.",
} as const;
