/** Every visible string of the default theme, gathered so that a locale catalogue can replace them. */
export const labels = {
  skipToContent: "Skip to content",
  siteNavigation: "Site",
  siteSearch: "Site search",
  search: "Search",
  searchSubmit: "Search",
  version: "version",
  builtOn: "built on",
  credit: "Built with Concordance",
  colourScheme: "Colour scheme",
  modeSystem: "automatic",
  modeLight: "light",
  modeDark: "dark",
  trailTitle: "Trail",
  trailPin: "Pin",
  trailUnpin: "Unpin",
  trailEmpty: "No page pinned yet",
  trailEarlier: "earlier pages",
  entryPoints: "Entry points",
  sources: "sources",
  files: "files",
  dormant: "dormant",
  shortcuts: "Most cited words",
  sourceFreshness: "Freshness of the sources",
  properties: "Properties",
  declaredAtTop: "Declared at the top of the file.",
  otherAttributes: "Other attributes",
  onThisPage: "On this page",
  spaceTree: "Tree of the space",
  breadcrumb: "You are here",
  legendWritten: "link written in the note",
  legendRecognised: "word recognised at indexing",
  correction: "Something to correct?",
  edit: "Edit this page",
  seeNeighbourhood: "See the neighbourhood map",
  neighbourPages: "pages",
  occurrences: "Occurrences",
  filesCount: "Files",
  sourcesCount: "Sources",
  passages: "Passages",
  line: "line",
  companions: "Accompanying words",
  noCompanion: "No accompanying word recorded.",
  similar: "Expressions with a similar form",
  relatedPages: "Related pages",
  filterPages: "Filter these pages",
  types: "Types",
  pagesOf: "{shown} of {total} pages",
  clearAll: "Clear all",
  cited: "Cited",
  passage: "passage",
  passagesOf: "passages",
  showOthers: "Show the {count} others",
  loadingOthers: "Loading the other pages",
  othersUnavailable: "The other pages could not be loaded.",
  fullList: "Open the full list (JSON)",
  orderNote:
    "Ordered by number of passages, written and recognised alike. \u201cCited\u201d marks a link present in the text.",
  noRelated: "No other page evokes this one yet.",
  noMatchingPage: "No page matches the filter.",
  neighbourhood: "Neighbourhood",
  neighbourhoodMap: "Map of the neighbourhood",
  neighbourhoodMapCaption: "The list below carries the same information as the map.",
  noNeighbour: "No neighbour recorded.",
  neighboursInTotal: "neighbours in total, more than the map shows",
  seeMentions: "see the mentions panel",
  resultsFor: "results for",
  facets: "Facets",
  activeFilters: "Active filters",
  removeFilter: "Remove this filter",
  clearFilters: "Clear filters",
  searchAddress: "Address of this search",
  copyAddress: "Copy",
  addressCopied: "Address copied",
  index: "Index",
  letters: "Letters",
  noteless: "no note",
  todo: "To do",
  documentsWithoutMarkdown: "Documents without a markdown representation",
  termsWithoutNote: "Words without a note",
  nothingToDo: "Nothing to do.",
  filesWithoutMarkdown: "Counted in files without a note.",
  occurrencesUnit: "Counted in occurrences, then in files.",
  document: "Document",
  download: "Download",
  openPdf: "Open the PDF",
  openViewer: "Open the viewer",
  closeViewer: "Close the viewer",
  viewerUnavailable: "The viewer could not be loaded",
  loadingViewer: "Loading the viewer",
  previousPage: "Previous",
  nextPage: "Next",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  findInDocument: "Find in the document",
  noMatch: "No match",
  matchesOn: "found on",
  pages: "Pages",
  slides: "Slides",
  cues: "Cues",
  extractedText: "Extracted text",
  noExtractedText: "No text was extracted from this document.",
  contract: "Contract",
  contractVersion: "version",
  contractImportedOn: "imported on",
  contractOperations: "Operations",
  contractNoOperation: "The contract declares no operation.",
  withoutNote: "without a note",
  noNoteYet: "no note yet",
  downloadContract: "Download the contract",
  contractData: "Contract data (JSON)",
  showContract: "Show the contract",
  hideContract: "Hide the contract",
  loadingContract: "Loading the contract…",
  contractUnavailable: "The contract could not be loaded.",
  contractSchemas: "Schemas",
  contractNoSchema: "The contract declares no schema.",
  parameters: "Parameters",
  parameterName: "Name",
  parameterIn: "In",
  parameterType: "Type",
  required: "required",
  request: "Request",
  responses: "Responses",
  responseStatus: "Status",
  responseBody: "Body",
  fieldName: "Field",
  fieldType: "Type",
  fieldDescription: "Description",
  noField: "No field.",
} as const;
