import type { JSX } from "preact";

import type { ShellProps } from "../../slots.js";
import { labels } from "./labels.js";

const ICON_TYPES: Readonly<Record<string, string>> = {
  svg: "image/svg+xml",
  png: "image/png",
  ico: "image/x-icon",
};

function iconType(href: string): string | undefined {
  return ICON_TYPES[href.toLowerCase().replace(/^.*\./, "")];
}

export function Shell({
  locale,
  direction,
  title,
  head,
  scheme,
  children,
}: ShellProps): JSX.Element {
  return (
    <html lang={locale} dir={direction} data-mode={scheme}>
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{title}</title>
        {head.redirect !== undefined && (
          <meta http-equiv="refresh" content={`0; url=${head.redirect}`} />
        )}
        {head.favicon !== undefined && (
          <link rel="icon" href={head.favicon} type={iconType(head.favicon)} />
        )}
        {(head.inlineScripts ?? []).map((script) => (
          // Generated by the renderer, never from content: the only script written inline.
          <script key={script} dangerouslySetInnerHTML={{ __html: script }} />
        ))}
        {head.stylesheets.map((href) => (
          <link key={href} rel="stylesheet" href={href} />
        ))}
        {head.modulePreloads.map((href) => (
          <link key={href} rel="modulepreload" href={href} />
        ))}
        {head.scripts.map((src) => (
          <script key={src} type="module" defer src={src} />
        ))}
        {(head.classicScripts ?? []).map((src) => (
          <script key={src} defer src={src} />
        ))}
      </head>
      <body>
        <a class="skip-link" href="#main">
          {labels.skipToContent}
        </a>
        {children}
      </body>
    </html>
  );
}
