// Assembles packages/profile/default.yaml, the profile the package loads, from
// packages/profile/base.yaml (everything but the types) and the type modules
// under packages/profile/types/<slug>/: type.yaml gives the declaration, the
// messages give the labels of the type, its attributes and its sections, and
// schema.json the schema of its list attributes. The types block is inserted
// before the relations, each type in slug order, so that the assembled file
// reads like the hand-written one. scripts/validate.mjs fails when the
// committed file differs from the assembly; the profile package tests check
// that its own reader assembles the same profile.
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { isMap, isSeq, parse as parseYaml, parseDocument } from "yaml";

// Code-unit order, never the collation of the runtime: the output is the same on every machine.
const byCodeUnit = (a, b) => Number(a > b) - Number(a < b);

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const baseFile = join(root, "packages/profile/base.yaml");
export const typesDirectory = join(root, "packages/profile/types");
export const profileFile = join(root, "packages/profile/default.yaml");

const HEADER = [
  "# Default profile of Concordance.",
  "#",
  "# GENERATED by scripts/assemble-profile.mjs from base.yaml and the type",
  "# modules under types/<slug>/: edit those, then run the script. The engine",
  "# knows nothing about screens, rules or glossaries: it reads this file.",
  "# A project profile is merged on top of it key by key. Types marked",
  "# `status: planned` are part of the meta-model but not yet rendered by the",
  "# first version; a project may enable them without any code change.",
  "#",
  "# Validated by packages/core/schemas/profile.schema.json.",
  "",
].join("\n");

function messageText(value) {
  return typeof value === "string" ? value : value.defaultMessage;
}

/** The messages of a module by language, each a flat record of final strings. */
function messagesOf(directory) {
  const folder = join(directory, "messages");
  const messages = {};
  if (!existsSync(folder)) return messages;
  for (const name of readdirSync(folder).sort(byCodeUnit)) {
    const language = /^([a-z]{2,3})\.json$/.exec(name)?.[1];
    if (language === undefined) continue;
    const document = JSON.parse(readFileSync(join(folder, name), "utf8"));
    messages[language] = Object.fromEntries(
      Object.entries(document).map(([key, value]) => [key, messageText(value)]),
    );
  }
  return messages;
}

function labelOf(messages, key) {
  const label = { en: messages.en?.[key] };
  if (messages.fr?.[key] !== undefined) label.fr = messages.fr[key];
  return label;
}

/** The type definition of the profile a module stands for, keys in the order of the hand-written profile. */
export function typeOf(directory) {
  const declaration = parseYaml(readFileSync(join(directory, "type.yaml"), "utf8"));
  const messages = messagesOf(directory);
  const schemaFile = join(directory, "schema.json");
  const schema = existsSync(schemaFile) ? JSON.parse(readFileSync(schemaFile, "utf8")) : {};
  const type = { label: labelOf(messages, "label") };
  for (const key of ["description", "counted"]) {
    if (messages.en?.[key] !== undefined) type[key] = labelOf(messages, key);
  }
  type.group = declaration.group;
  for (const key of ["status", "glyph", "graph"]) {
    if (declaration[key] !== undefined) type[key] = declaration[key];
  }
  if (declaration.attributes !== undefined) {
    type.attributes = Object.fromEntries(
      Object.entries(declaration.attributes).map(([name, attribute]) => {
        const labelled = { ...attribute };
        if (messages.en?.[`attributes.${name}`] !== undefined) {
          labelled.label = labelOf(messages, `attributes.${name}`);
        }
        if (labelled.schema === undefined && schema[name] !== undefined) {
          labelled.schema = schema[name];
        }
        return [name, labelled];
      }),
    );
  }
  if (declaration.sections !== undefined) {
    type.sections = Object.fromEntries(
      Object.entries(declaration.sections).map(([key, section]) => [
        key,
        { heading: labelOf(messages, `sections.${key}`), ...section },
      ]),
    );
  }
  if (declaration.display !== undefined) type.display = declaration.display;
  return type;
}

/** Every module of the folder, in slug order. */
export function modulesOf(directory) {
  return readdirSync(directory)
    .filter((name) => existsSync(join(directory, name, "type.yaml")))
    .sort(byCodeUnit)
    .map((slug) => ({ slug, type: typeOf(join(directory, slug)) }));
}

/** Labels, attribute definitions, section attributes and display lists on one line, as the hand-written profile had them. */
function flowLeaves(node, path) {
  if (!isMap(node)) return;
  for (const pair of node.items) {
    const at = [...path, String(pair.key)];
    const value = pair.value;
    const leaf =
      ["label", "heading"].includes(at.at(-1)) ||
      (at.length === 2 && (at[0] === "attributes" || at[0] === "display")) ||
      (at.length === 3 && at[0] === "sections" && at[2] === "attributes");
    if (leaf && (isMap(value) || isSeq(value))) {
      value.flow = true;
    } else {
      flowLeaves(value, at);
    }
  }
}

/** The assembled profile as YAML text: the base with its comments, the types block before the relations. */
export function assembleProfileText() {
  const document = parseDocument(readFileSync(baseFile, "utf8"));
  const types = document.createNode({});
  for (const { slug, type } of modulesOf(typesDirectory)) {
    const node = document.createNode(type);
    flowLeaves(node, []);
    const key = document.createNode(slug);
    key.spaceBefore = types.items.length > 0;
    types.items.push(document.createPair(key, node));
  }
  const key = document.createNode("types");
  key.spaceBefore = true;
  const relations = document.contents.items.findIndex((pair) => String(pair.key) === "relations");
  document.contents.items.splice(relations, 0, document.createPair(key, types));
  const text = document.toString({ lineWidth: 0 });
  const body = text.replace(/^(#[^\n]*\n)+\n?/, "");
  return `${HEADER}\n${body}`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const text = assembleProfileText();
  writeFileSync(profileFile, text);
  console.log(
    `${profileFile}: assembled from ${String(modulesOf(typesDirectory).length)} type modules`,
  );
}
