import { describe, expect, it } from "vitest";

import * as entry from "../src/index.js";

describe("@concordance-wiki/inference", () => {
  it("exposes exactly its public API", () => {
    expect(Object.keys(entry).sort()).toEqual([
      "CONTRACT_REPRESENTATION",
      "DUPLICATE_CHECK",
      "DUPLICATE_DEFAULTS",
      "FALLBACK_RELATION",
      "MATCH_RUNGS",
      "MAX_DISPLAYED_NEIGHBOURS",
      "OPERATION_AMBIGUOUS",
      "OPERATION_UNMATCHED",
      "RELATION_ORIGIN",
      "accumulateCooccurrences",
      "attachOperations",
      "buildGraph",
      "combineConfidences",
      "combineLinks",
      "combineOptions",
      "comparePivots",
      "cooccurrenceLinks",
      "displayOptions",
      "displayedNeighbourhood",
      "displayedNeighbourhoodToModel",
      "distancesFrom",
      "duplicateOptions",
      "emergentDomainsOptions",
      "explicitLinks",
      "foldHeading",
      "formatDuplicateStats",
      "frontmatterLinks",
      "glossaryConfidence",
      "importedOperations",
      "indexEntities",
      "locateLink",
      "mappedSection",
      "matchOperations",
      "mentionLinks",
      "mergeOperation",
      "neighbourhoodOptions",
      "neighbourhoodToModel",
      "operationNotes",
      "proposeEmergentDomains",
      "redirectLinks",
      "relationLabel",
      "resolveDuplicateResources",
      "resolveReference",
      "selectPivots",
      "typeRelations",
    ]);
  });
});
